// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// source: proto/game/message.proto

package game

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNKNOWN       MessageType = 0
	MessageType_MESSAGE_TYPE_HEARTBEAT     MessageType = 1
	MessageType_MESSAGE_TYPE_CHAT          MessageType = 2
	MessageType_MESSAGE_TYPE_ROOM_NOTICE   MessageType = 3
	MessageType_MESSAGE_TYPE_GAME_ACTION   MessageType = 4
	MessageType_MESSAGE_TYPE_SYSTEM_NOTICE MessageType = 5
)

var MessageType_name = map[int32]string{
	0: "MESSAGE_TYPE_UNKNOWN",
	1: "MESSAGE_TYPE_HEARTBEAT",
	2: "MESSAGE_TYPE_CHAT",
	3: "MESSAGE_TYPE_ROOM_NOTICE",
	4: "MESSAGE_TYPE_GAME_ACTION",
	5: "MESSAGE_TYPE_SYSTEM_NOTICE",
}

var MessageType_value = map[string]int32{
	"MESSAGE_TYPE_UNKNOWN":       0,
	"MESSAGE_TYPE_HEARTBEAT":     1,
	"MESSAGE_TYPE_CHAT":          2,
	"MESSAGE_TYPE_ROOM_NOTICE":   3,
	"MESSAGE_TYPE_GAME_ACTION":   4,
	"MESSAGE_TYPE_SYSTEM_NOTICE": 5,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_game_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	RoomId    string `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Timestamp int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ChatMessage) Reset()                             { *x = ChatMessage{} }
func (x *ChatMessage) String() string                     { return "" }
func (*ChatMessage) ProtoMessage()                        {}
func (x *ChatMessage) ProtoReflect() protoreflect.Message { return nil }

func (x *ChatMessage) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChatMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RoomNotice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	NoticeType string `protobuf:"bytes,2,opt,name=notice_type,json=noticeType,proto3" json:"notice_type,omitempty"`
	UserId     int64  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username   string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Content    string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp  int64  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *RoomNotice) Reset()                             { *x = RoomNotice{} }
func (x *RoomNotice) String() string                     { return "" }
func (*RoomNotice) ProtoMessage()                        {}
func (x *RoomNotice) ProtoReflect() protoreflect.Message { return nil }

func (x *RoomNotice) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomNotice) GetNoticeType() string {
	if x != nil {
		return x.NoticeType
	}
	return ""
}

func (x *RoomNotice) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RoomNotice) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RoomNotice) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RoomNotice) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GameAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId     int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActionType string `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Data       []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp  int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *GameAction) Reset()                             { *x = GameAction{} }
func (x *GameAction) String() string                     { return "" }
func (*GameAction) ProtoMessage()                        {}
func (x *GameAction) ProtoReflect() protoreflect.Message { return nil }

func (x *GameAction) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameAction) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GameAction) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *GameAction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GameAction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SystemNotice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title     string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content   string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *SystemNotice) Reset()                             { *x = SystemNotice{} }
func (x *SystemNotice) String() string                     { return "" }
func (*SystemNotice) ProtoMessage()                        {}
func (x *SystemNotice) ProtoReflect() protoreflect.Message { return nil }

func (x *SystemNotice) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SystemNotice) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SystemNotice) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type WSMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=game.MessageType" json:"type,omitempty"`
	Data      []byte      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp int64       `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RequestId string      `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *WSMessage) Reset()                             { *x = WSMessage{} }
func (x *WSMessage) String() string                     { return "" }
func (*WSMessage) ProtoMessage()                        {}
func (x *WSMessage) ProtoReflect() protoreflect.Message { return nil }

func (x *WSMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNKNOWN
}

func (x *WSMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WSMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WSMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type WSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=game.MessageType" json:"type,omitempty"`
	Data      []byte      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp int64       `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RequestId string      `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *WSRequest) Reset()                             { *x = WSRequest{} }
func (x *WSRequest) String() string                     { return "" }
func (*WSRequest) ProtoMessage()                        {}
func (x *WSRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *WSRequest) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNKNOWN
}

func (x *WSRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WSRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WSRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type WSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=game.MessageType" json:"type,omitempty"`
	Code      int32       `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message   string      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data      []byte      `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp int64       `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RequestId string      `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *WSResponse) Reset()                             { *x = WSResponse{} }
func (x *WSResponse) String() string                     { return "" }
func (*WSResponse) ProtoMessage()                        {}
func (x *WSResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *WSResponse) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNKNOWN
}

func (x *WSResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WSResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WSResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WSResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WSResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *HeartbeatRequest) Reset()                             { *x = HeartbeatRequest{} }
func (x *HeartbeatRequest) String() string                     { return "" }
func (*HeartbeatRequest) ProtoMessage()                        {}
func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTimestamp int64 `protobuf:"varint,1,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
}

func (x *HeartbeatResponse) Reset()                             { *x = HeartbeatResponse{} }
func (x *HeartbeatResponse) String() string                     { return "" }
func (*HeartbeatResponse) ProtoMessage()                        {}
func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *HeartbeatResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

type SendChatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId  string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *SendChatRequest) Reset()                             { *x = SendChatRequest{} }
func (x *SendChatRequest) String() string                     { return "" }
func (*SendChatRequest) ProtoMessage()                        {}
func (x *SendChatRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *SendChatRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendChatRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendChatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendChatResponse) Reset()                             { *x = SendChatResponse{} }
func (x *SendChatResponse) String() string                     { return "" }
func (*SendChatResponse) ProtoMessage()                        {}
func (x *SendChatResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *SendChatResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendChatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BroadcastRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string      `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Type   MessageType `protobuf:"varint,2,opt,name=type,proto3,enum=game.MessageType" json:"type,omitempty"`
	Data   []byte      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BroadcastRequest) Reset()                             { *x = BroadcastRequest{} }
func (x *BroadcastRequest) String() string                     { return "" }
func (*BroadcastRequest) ProtoMessage()                        {}
func (x *BroadcastRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *BroadcastRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *BroadcastRequest) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNKNOWN
}

func (x *BroadcastRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BroadcastResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BroadcastResponse) Reset()                             { *x = BroadcastResponse{} }
func (x *BroadcastResponse) String() string                     { return "" }
func (*BroadcastResponse) ProtoMessage()                        {}
func (x *BroadcastResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *BroadcastResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BroadcastResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_game_message_proto protoreflect.FileDescriptor

var file_proto_game_message_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65,
	0x2a, 0x8a, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1c, 0x0a, 0x18, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x4d, 0x45,
	0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x48, 0x45, 0x41, 0x52, 0x54,
	0x42, 0x45, 0x41, 0x54, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x10, 0x02, 0x12, 0x1c, 0x0a,
	0x18, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x4f,
	0x4f, 0x4d, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x10, 0x03, 0x12, 0x1c, 0x0a, 0x18, 0x4d,
	0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x41, 0x4d, 0x45,
	0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x04, 0x12, 0x1d, 0x0a, 0x19, 0x4d, 0x45, 0x53,
	0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d,
	0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x10, 0x05, 0x42, 0x14, 0x5a, 0x12, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_game_message_proto_rawDescOnce sync.Once
	file_proto_game_message_proto_rawDescData = file_proto_game_message_proto_rawDesc
)

func file_proto_game_message_proto_rawDescGZIP() []byte {
	file_proto_game_message_proto_rawDescOnce.Do(func() {
		file_proto_game_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_game_message_proto_rawDescData)
	})
	return file_proto_game_message_proto_rawDescData
}

var file_proto_game_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_game_message_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_game_message_proto_goTypes = []interface{}{
	(MessageType)(0),
	(*ChatMessage)(nil),
	(*RoomNotice)(nil),
	(*GameAction)(nil),
	(*SystemNotice)(nil),
	(*WSMessage)(nil),
	(*WSRequest)(nil),
	(*WSResponse)(nil),
	(*HeartbeatRequest)(nil),
	(*HeartbeatResponse)(nil),
	(*SendChatRequest)(nil),
	(*SendChatResponse)(nil),
	(*BroadcastRequest)(nil),
	(*BroadcastResponse)(nil),
}

func init() { file_proto_game_message_proto_init() }

func file_proto_game_message_proto_init() {
	if File_proto_game_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_game_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_game_message_proto_goTypes,
		DependencyIndexes: []int32{},
		EnumInfos:         file_proto_game_message_proto_enumTypes,
		MessageInfos:      file_proto_game_message_proto_msgTypes,
	}.Build()
	File_proto_game_message_proto = out.File
	file_proto_game_message_proto_rawDesc = nil
	file_proto_game_message_proto_goTypes = nil
}
