// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// source: proto/game/room.proto

package game

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomType int32

const (
	RoomType_ROOM_TYPE_UNKNOWN RoomType = 0
	RoomType_ROOM_TYPE_PUBLIC  RoomType = 1
	RoomType_ROOM_TYPE_PRIVATE RoomType = 2
)

var RoomType_name = map[int32]string{
	0: "ROOM_TYPE_UNKNOWN",
	1: "ROOM_TYPE_PUBLIC",
	2: "ROOM_TYPE_PRIVATE",
}

var RoomType_value = map[string]int32{
	"ROOM_TYPE_UNKNOWN": 0,
	"ROOM_TYPE_PUBLIC":  1,
	"ROOM_TYPE_PRIVATE": 2,
}

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_room_proto_enumTypes[0].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_proto_game_room_proto_enumTypes[0]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type RoomStatus int32

const (
	RoomStatus_ROOM_STATUS_UNKNOWN  RoomStatus = 0
	RoomStatus_ROOM_STATUS_WAITING  RoomStatus = 1
	RoomStatus_ROOM_STATUS_PLAYING  RoomStatus = 2
	RoomStatus_ROOM_STATUS_FINISHED RoomStatus = 3
)

var RoomStatus_name = map[int32]string{
	0: "ROOM_STATUS_UNKNOWN",
	1: "ROOM_STATUS_WAITING",
	2: "ROOM_STATUS_PLAYING",
	3: "ROOM_STATUS_FINISHED",
}

var RoomStatus_value = map[string]int32{
	"ROOM_STATUS_UNKNOWN":  0,
	"ROOM_STATUS_WAITING":  1,
	"ROOM_STATUS_PLAYING":  2,
	"ROOM_STATUS_FINISHED": 3,
}

func (x RoomStatus) Enum() *RoomStatus {
	p := new(RoomStatus)
	*p = x
	return p
}

func (x RoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_room_proto_enumTypes[1].Descriptor()
}

func (RoomStatus) Type() protoreflect.EnumType {
	return &file_proto_game_room_proto_enumTypes[1]
}

func (x RoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type RoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId         string     `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomName       string     `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	RoomType       RoomType   `protobuf:"varint,3,opt,name=room_type,json=roomType,proto3,enum=game.RoomType" json:"room_type,omitempty"`
	Status         RoomStatus `protobuf:"varint,4,opt,name=status,proto3,enum=game.RoomStatus" json:"status,omitempty"`
	MaxPlayers     int32      `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	CurrentPlayers int32      `protobuf:"varint,6,opt,name=current_players,json=currentPlayers,proto3" json:"current_players,omitempty"`
	OwnerId        int64      `protobuf:"varint,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Password       string     `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	PlayerIds      []int64    `protobuf:"varint,9,rep,packed,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	CreateTime     int64      `protobuf:"varint,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *RoomInfo) Reset()                             { *x = RoomInfo{} }
func (x *RoomInfo) String() string                     { return "" }
func (*RoomInfo) ProtoMessage()                        {}
func (x *RoomInfo) ProtoReflect() protoreflect.Message { return nil }

func (x *RoomInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomInfo) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomInfo) GetRoomType() RoomType {
	if x != nil {
		return x.RoomType
	}
	return RoomType_ROOM_TYPE_UNKNOWN
}

func (x *RoomInfo) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_UNKNOWN
}

func (x *RoomInfo) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *RoomInfo) GetCurrentPlayers() int32 {
	if x != nil {
		return x.CurrentPlayers
	}
	return 0
}

func (x *RoomInfo) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *RoomInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RoomInfo) GetPlayerIds() []int64 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *RoomInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RoomName   string   `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	RoomType   RoomType `protobuf:"varint,3,opt,name=room_type,json=roomType,proto3,enum=game.RoomType" json:"room_type,omitempty"`
	MaxPlayers int32    `protobuf:"varint,4,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	Password   string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *CreateRoomRequest) Reset()                             { *x = CreateRoomRequest{} }
func (x *CreateRoomRequest) String() string                     { return "" }
func (*CreateRoomRequest) ProtoMessage()                        {}
func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *CreateRoomRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateRoomRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *CreateRoomRequest) GetRoomType() RoomType {
	if x != nil {
		return x.RoomType
	}
	return RoomType_ROOM_TYPE_UNKNOWN
}

func (x *CreateRoomRequest) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *CreateRoomRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Room    *RoomInfo `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *CreateRoomResponse) Reset()                             { *x = CreateRoomResponse{} }
func (x *CreateRoomResponse) String() string                     { return "" }
func (*CreateRoomResponse) ProtoMessage()                        {}
func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *CreateRoomResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateRoomResponse) GetRoom() *RoomInfo {
	if x != nil {
		return x.Room
	}
	return nil
}

type JoinRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RoomId   string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *JoinRoomRequest) Reset()                             { *x = JoinRoomRequest{} }
func (x *JoinRoomRequest) String() string                     { return "" }
func (*JoinRoomRequest) ProtoMessage()                        {}
func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *JoinRoomRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Room    *RoomInfo `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *JoinRoomResponse) Reset()                             { *x = JoinRoomResponse{} }
func (x *JoinRoomResponse) String() string                     { return "" }
func (*JoinRoomResponse) ProtoMessage()                        {}
func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *JoinRoomResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JoinRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinRoomResponse) GetRoom() *RoomInfo {
	if x != nil {
		return x.Room
	}
	return nil
}

type LeaveRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *LeaveRoomRequest) Reset()                             { *x = LeaveRoomRequest{} }
func (x *LeaveRoomRequest) String() string                     { return "" }
func (*LeaveRoomRequest) ProtoMessage()                        {}
func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *LeaveRoomRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LeaveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type LeaveRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LeaveRoomResponse) Reset()                             { *x = LeaveRoomResponse{} }
func (x *LeaveRoomResponse) String() string                     { return "" }
func (*LeaveRoomResponse) ProtoMessage()                        {}
func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *LeaveRoomResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LeaveRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRoomListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	RoomType RoomType `protobuf:"varint,3,opt,name=room_type,json=roomType,proto3,enum=game.RoomType" json:"room_type,omitempty"`
}

func (x *GetRoomListRequest) Reset()                             { *x = GetRoomListRequest{} }
func (x *GetRoomListRequest) String() string                     { return "" }
func (*GetRoomListRequest) ProtoMessage()                        {}
func (x *GetRoomListRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *GetRoomListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRoomListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetRoomListRequest) GetRoomType() RoomType {
	if x != nil {
		return x.RoomType
	}
	return RoomType_ROOM_TYPE_UNKNOWN
}

type GetRoomListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Rooms   []*RoomInfo `protobuf:"bytes,3,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Total   int32       `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetRoomListResponse) Reset()                             { *x = GetRoomListResponse{} }
func (x *GetRoomListResponse) String() string                     { return "" }
func (*GetRoomListResponse) ProtoMessage()                        {}
func (x *GetRoomListResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *GetRoomListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRoomListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRoomListResponse) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *GetRoomListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetRoomInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *GetRoomInfoRequest) Reset()                             { *x = GetRoomInfoRequest{} }
func (x *GetRoomInfoRequest) String() string                     { return "" }
func (*GetRoomInfoRequest) ProtoMessage()                        {}
func (x *GetRoomInfoRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *GetRoomInfoRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetRoomInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Room    *RoomInfo `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *GetRoomInfoResponse) Reset()                             { *x = GetRoomInfoResponse{} }
func (x *GetRoomInfoResponse) String() string                     { return "" }
func (*GetRoomInfoResponse) ProtoMessage()                        {}
func (x *GetRoomInfoResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *GetRoomInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRoomInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRoomInfoResponse) GetRoom() *RoomInfo {
	if x != nil {
		return x.Room
	}
	return nil
}

var File_proto_game_room_proto protoreflect.FileDescriptor

var file_proto_game_room_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x72, 0x6f, 0x6f,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x2a, 0x4c, 0x0a,
	0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x4f, 0x4f,
	0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x17, 0x0a, 0x13, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x55,
	0x42, 0x4c, 0x49, 0x43, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x50, 0x52, 0x49, 0x56, 0x41, 0x54, 0x45, 0x10, 0x02, 0x2a, 0x60, 0x0a,
	0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x15, 0x52,
	0x4f, 0x4f, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x57, 0x41, 0x49, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x19, 0x0a,
	0x15, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x4c, 0x41,
	0x59, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x03,
	0x42, 0x14, 0x5a, 0x12, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_game_room_proto_rawDescOnce sync.Once
	file_proto_game_room_proto_rawDescData = file_proto_game_room_proto_rawDesc
)

func file_proto_game_room_proto_rawDescGZIP() []byte {
	file_proto_game_room_proto_rawDescOnce.Do(func() {
		file_proto_game_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_game_room_proto_rawDescData)
	})
	return file_proto_game_room_proto_rawDescData
}

var file_proto_game_room_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_game_room_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_game_room_proto_goTypes = []interface{}{
	(RoomType)(0),
	(RoomStatus)(0),
	(*RoomInfo)(nil),
	(*CreateRoomRequest)(nil),
	(*CreateRoomResponse)(nil),
	(*JoinRoomRequest)(nil),
	(*JoinRoomResponse)(nil),
	(*LeaveRoomRequest)(nil),
	(*LeaveRoomResponse)(nil),
	(*GetRoomListRequest)(nil),
	(*GetRoomListResponse)(nil),
	(*GetRoomInfoRequest)(nil),
	(*GetRoomInfoResponse)(nil),
}

func init() { file_proto_game_room_proto_init() }

func file_proto_game_room_proto_init() {
	if File_proto_game_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_game_room_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_game_room_proto_goTypes,
		DependencyIndexes: []int32{},
		EnumInfos:         file_proto_game_room_proto_enumTypes,
		MessageInfos:      file_proto_game_room_proto_msgTypes,
	}.Build()
	File_proto_game_room_proto = out.File
	file_proto_game_room_proto_rawDesc = nil
	file_proto_game_room_proto_goTypes = nil
}
